config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "flights#index"
  resources :flights
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id"
  belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    if (params[:departure_airport].present? && params[:arrival_airport].present?)
      @flights = @flights.where(
        departure_airport_id: Airport.find_by(code: params[:departure_airport].strip),
        arrival_airport_id: Airport.find_by(code: params[:arrival_airport].strip),
        )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def get_airport_code(airport_id)
    Airport.find_by(id: airport_id).code
  end
end

app/views/flights/_flight.html.erb
<div class="flight-info">
    <br>
    <p>Flight <%= flight.id %></p>
    <p>From <%= get_airport_code(flight.departure_airport_id) %> to <%= get_airport_code(flight.arrival_airport_id) %> is <%= flight.duration %> hours long.</p>
    <p>Plane departs <%= get_airport_code(flight.departure_airport_id) %> at <%= flight.start %>,</p>
    <p>and lands at <%= get_airport_code(flight.arrival_airport_id) %> around <%= flight.finish %>.</p>
    <br>
</div>

app/views/flights/_form.html.erb
<form class="form-inline w-100">
    <%= form_with url: flights_path, method: :get do |f| %>
    <div class="form-field">
        <%= f.text_field :departure_airport, placeholder: :departure_airport%>
    </div>

    <div class="form-field">
        <%= f.text_field :arrival_airport, placeholder: :arrival_airport%>
    </div>

    <div class="form-field">
        <%= f.date_field :date_of_departure%>
    </div>

    <div class="form-field">
        <%= f.number_field :number_of_passengers, in: 1..10, step: 1, placeholder: :number_of_passengers%>
    </div>

    <%= f.submit :Search%>
    <%end%>
</form>

app/views/flights/index.html.erb
<h1>Current flights</h1>
<div class="w-100">
    <%= button_to "View All", root_path, method: :get %>
    <%= render "form"%>
</div>

<% if (@flights.length > 0) %>
  <%= form_with url: "/", method: :get do |f| %>
    <% @flights.each do |flight| %>
      <div>
        <%= f.radio_button :flight_id, flight.id, id: "flight_#{flight.id}"%>
        <%= f.label "#{flight.id}" do %>
          <%= render flight %>
        <% end %>
      </div>
    <% end %>
    <%= f.submit :Book %>
  <% end %>
<% else %>
  <p>Sorry, no flights were found. :(</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <%= yield %>
</body>

</html>